### ISSUE TITLE
Push 2.0.1 to npmjs.com?

### ISSUE THREAD

**Issue by chriskinsman** [jsantell/s3-stream-upload#13]
Thanks! @jsantell

**Comment by jsantell** [comment]
Hey Chris, just [published 2.0.1](https://www.npmjs.com/package/s3-stream-upload)! Also, you've been contributing a bit to this so I added you as a collaborator -- if you give me your npm name, I can give you permission on there too. Let me know, and thank you for your work!

**Comment by chriskinsman** [comment]
Thanks for doing that!  I am chriskinsman on npm.

**Comment by jsantell** [comment]
Great! Added you to the project. Thanks again!
