### ISSUE TITLE
Add Short, Self Contained, Correct Example to Readme

### ISSUE THREAD

**Issue by morenoh149** [jsantell/s3-stream-upload#16]
I'm evaluating this module. The example in the readme does not run, below is as far as I got
```es
// index.js
var UploadStream = require("s3-stream-upload");
var S3 = require("aws-sdk").S3;
var fs = require("fs");

var key = "file.mp3";
var s3 = new S3();

var contents = fs.readFileSync(__dirname + "/file.mp3");
UploadStream(s3, { Bucket: "my-bucket", Key: key })
  .write(contents)
```
* required `fs` module
* replaced `readFileStream` as it's not in the fs api
* currently stuck on how to `pipe` a file to the `UploadStream` object
```sh
$ node index.js
foo/s3test/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
```

**Comment by jsantell** [comment]
This is an older module and one I haven't used in some time, not sure how it fairs with the current Node APIs and state of streams. I'm guessing `readFileStream` should be updated to [fs.createReadStream](https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options), as using `readFileSync` defeats the purpose of this lib -- the idea is to never store the whole file in memory and just pass it along to AWS. A quick look at the current [Stream](https://nodejs.org/api/stream.html) docs, it looks like the streaming should still be OK though
