### ISSUE TITLE
Throws error during upload

### ISSUE THREAD

**Issue by chriskinsman** [jsantell/s3-stream-upload#3]
When uploading now this line throws:
self.emit("chunk-uploaded", self._uploader._uploaded.length);

Digging through the code it doesn't look like the _uploader has a _uploaded to get the length from hence the issue.  I think the intention is to include how much of the file has uploaded with the emitted event but wasn't sure.

Looking at the tests _uploaded appears to only exist on the mock and not the real item

**Comment by jsantell** [comment]
fixed via af4ab5959d72ffa1208cc846b1ebbfe7bf2e8cb6
